### ISSUE TITLE
Inline notes problem

### ISSUE THREAD

**Issue by kysko** [tarleb/panluna#2]
The result of inline notes seem a bit off.

From your tests for example,

```
This summer^[It wasn't very summerly.] was short.
```

gives

```
Para
    [ Str "This"
    , Space
    , Str "summer"
    , Note
        [ Plain [ Str "It" ]
        , Plain [ Space ]
        , Plain [ Str "wasn't" ]
        , Plain [ Space ]
        , Plain [ Str "very" ]
        , Plain [ Space ]
        , Plain [ Str "summerly." ]
        ]
    , Space
    , Str "was"
    , Space
    , Str "short."
    ]
```

but should give something like:

```
Para
    [ Str "This"
    , Space
    , Str "summer"
    , Note
        [ Para
            [ Str "It"
            , Space
            , Str "wasn't"
            , Space
            , Str "very"
            , Space
            , Str "summerly."
            ]
        ]
    , Space
    , Str "was"
    , Space
    , Str "short"
    , Str "."
    ]
```

In case of inline notes, the argument lunamark sends write.note is the result from a parse_inlines, rather than a parse_blocks.

When unroping the argument sent for inline notes, I see we get a List of Inline's, not Block's like in indirect link.

~For now, what works for me is:~

**/Edit:** Argh! The solution I proposed **did not** work: there could be reference links in the note itself. I'll leave it to the expert!

**Comment by tarleb** [comment]
Thanks!
